config/routes.rb
OpenLets::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }

  resources :economies

  resources :users do
    member do
      post :direct_transfer
      get  :transfer
    end
    collection do
      get :complete_profile
    end
  end

  resources :members do
    member do
      post :direct_transfer
      get  :transfer
    end
  end
  
  resources :items do
    member do
      get  :purchase_details
      post :time_purchase
      post :purchase
      put  :pause
      put  :activate
    end
    resources :comments, only: [:create]
  end
  
  resources :wishes do
    member do
      put  :pause
      put  :activate
      get  :fulfill
      put  :close
      post :create_wish_offer
    end
  end

  resources :conversations, only: [:index, :show] do
    resources :messages, only: [:create, :index]
    collection do
      get  '/:user_id/new',    to: 'conversations#new',    as: :new
      post '/:user_id/create', to: 'conversations#create', as: :create
    end
  end

  constraints DomainConstraint.new do
    root to: 'pages#economy_home'

    namespace :admin do
      root to: "admin#dashboard", as: :dashboard
      resources :members do
        put :approve
        put :ban
      end
      resources :users do
        member do
          put :approve
          put :ban
        end    
      end
      resources :managers do
        collection do
          put 'add'
          delete 'remove'
        end 
      end
      resources :items do
        member do
          put :activate
          put :pause
          put :ban
        end
      end
      resources :wishes
      resources :comments
      resources :settings do
        collection do
          get :mass_edit
          put :mass_update
        end
      end
      resources :transactions do
        member do
          put :cancel
        end
      end
      resources :categories
      resources :economies, only: :update
    end

  end

  namespace :realm do
    root to: "realm#dashboard", as: :dashboard
    
    resources :admins do
      collection do
        put    :add
        delete :remove
      end      
    end

    resources :users
    resources :economies
  end

  get "pages/terms"
  get "pages/welcome"
  get "pages/faq"

  root to: 'pages#home'
end

app/models/economy.rb
class Economy < ActiveRecord::Base
  include Filterable

  attr_accessible :currency_name, :description, :economy_type, :title, :currency_type,
                  :domain, :max_debit, :max_credit, :allow_anyone_to_create_items,
                  :allow_anyone_to_create_wishes, :invite_only, :logo, :bg_image,
                  :zero_point, :faq, :title_color, :seo_title, :big_logo, :seo_description,
                  :item_title_placeholder, :item_description_placeholder, 
                  :wish_title_placeholder, :wish_description_placeholder,
                  :add_item_form_title, :add_wish_form_title
  
  validates_presence_of :title, :economy_type, :currency_name, :currency_type, 
                        :domain, :user_id, :item_title_placeholder, 
                        :item_description_placeholder, :wish_title_placeholder, 
                        :wish_description_placeholder, :add_item_form_title,
                        :add_wish_form_title

  mount_uploader :bg_image, ImageUploader
  mount_uploader :logo,     ImageUploader
  mount_uploader :big_logo, ImageUploader

  belongs_to :user
  has_many :members
  has_many :items,  through: :members
  has_many :wishes, through: :members
  has_many :users,  through: :members
  has_many :categories
  has_many :wallets
  has_many :transactions

  after_create :add_admin_role

  before_validation :load_economy_validations

  def load_economy_validations
    self.class.send(:include, "MonetaryModels::#{self.currency_type.camelcase}::Economy".constantize)
  end

  ECONOMY_TYPES  = %w(community cooperative business non_profit)
  CURRENCY_TYPES = %w(time_bank mutual_credit)
   # fiat backed linked

  def managers
    users.joins(:roles).where("roles.resource_id = ? OR roles.name='admin'", id).uniq
  end

  def add_admin_role
    self.user.add_role :manager, self
  end

  def self.realm_attributes_for_table
    [:id, :logo, :bg_image, :title, :user_id, :domain, :economy_type, :currency_type]
  end

  def self.attributes_for_table
    [:id, :logo, :bg_image, :title, :user_id, :domain, :economy_type]
  end

  def self.admin_filter_attr_names
    [:id, :title, :description, :currency_name, :currency_type, :domain, :economy_type]
  end

  def currency_type_is?(model)
    currency_type == model.to_s
  end

  def time_bank?
    currency_type == "time_bank"
  end

end

app/models/monetary_models/mutual_credit/economy.rb
module MonetaryModels
  module MutualCredit
    module Economy
      extend ActiveSupport::Concern

      included do
        validates_presence_of :max_debit, :max_credit
      end

      module ClassMethods
      end
    end
  end
end

app/models/monetary_models/time_bank/economy.rb
module MonetaryModels
  module TimeBank
    module Economy
      extend ActiveSupport::Concern

      included do
        validates_presence_of :max_debit, :max_credit
      end

      module ClassMethods
      end
    end
  end
end

app/controllers/admin/economies_controller.rb
class Admin::EconomiesController < Admin::ResourceController

  def update
    @economy = resource
    if @economy.update_attributes(params[:economy])
      flash[:notice] = t('flash_messages.economy_updated_successfully')
      redirect_to admin_settings_path
    else
      render 'admin/settings/economy_settings'
    end
  end

  private
    
    def filtered_collection
      @filtered_collection ||= end_of_association_chain.order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 10)
    end

end

app/controllers/economies_controller.rb
class EconomiesController < ApplicationController
  load_and_authorize_resource
  inherit_resources

  protected
    def begin_of_association_chain
      current_user
    end  
end

app/controllers/realm/economies_controller.rb
class Realm::EconomiesController < Realm::ResourceController

  private
    
    def filtered_collection
      @filtered_collection ||= Economy.filter_for(filter_params).order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 10)
    end

end

app/helpers/economy_helper.rb
module EconomyHelper

  def invite_only
    current_economy ? current_economy.invite_only : false
  end

  def currency_name
    current_economy.time_bank? ? t('activerecord.attributes.economy.time_bank.currency_name') : current_economy.currency_name
  end

end

app/views/economies/_form.slim
= simple_form_for @economy, wrapper: :foundation_inline do |f|
  = f.error_notification

  = f.input :title,         required: true, autofocus: true, label: t('forms.title')
  = f.input :description,   required: true, label: t('forms.description')
  = f.input :currency_name, required: true, label: t('forms.currency_name')
  
  = render 'partials/boolean', attribute: "allow_anyone_to_create_items", f: f
  = render 'partials/boolean', attribute: "allow_anyone_to_create_wishes", f: f
  = render 'partials/boolean', attribute: "invite_only", f: f

  = f.input :domain,        required: true, label: t('forms.domain'),as: :url
  - if f.object.persisted?
    = f.input :currency_type, required: true, label: t('forms.currency_type'), disabled: true, input_html: { value: f.object.currency_type.titleize }
    = f.input :economy_type,  required: true, label: t('forms.economy_type'), disabled: true, input_html: { value: f.object.economy_type.titleize }
  - else
    = f.input :currency_type, required: true, label: t('forms.currency_type'), collection: Economy::CURRENCY_TYPES.map { |c| [c.titleize, c] }
    = f.input :economy_type,  required: true, label: t('forms.economy_type'), collection: Economy::ECONOMY_TYPES.map { |c| [c.titleize, c] }
  - if ["mutual_credit", "time_bank"].include?(f.object.currency_type)
    = f.input :max_debit, label: t('forms.max_debit')
    = f.input :max_credit, label: t('forms.max_credit')
    = f.input :zero_point, label: t('forms.zero_point')
    
  = f.input :logo
  = f.input :bg_image
  .row
    .large-3.columns
    .large-9.columns
      = f.button :submit, t('forms.update')

app/views/economies/_table.slim
.row
  .large-12.columns
    h1.text-center.bold= t('activerecord.models.economy', count: 3)
    ul.small-block-grid-3
      - economies.each do |economy|
        li.panel
          h3.bold= economy.title
          p= economy.description
          p= "Members: #{economy.members.count}"
          p= "Economy Type: #{economy.economy_type}"
          p= "Currency Name: #{economy.currency_name}"
          p= "Economic Model: #{economy.currency_type.titleize}"
          = link_to "Join", economy.domain, class: 'button radius'
          - if can? :edit, economy
            = link_to "Edit", edit_economy_path(economy), class: 'button radius'

app/views/economies/edit.slim
.row
  .large-12.columns
    h1.text-center= "Edit Economy"
    == render 'form'

app/views/economies/new.slim
.row
  .large-12.columns
    h1.text-center.bold= t('forms.new_economy')
    == render 'form'

app/views/economies/show.slim
.row
  .large-12.columns
    h1.bold= @economy.title
    p= @economy.description
    p= "Members: #{@economy.members.count}"
    p= "Economy Type: #{@economy.economy_type}"
    p= "Currency Name: #{@economy.currency_name}"
    p= "Economic Model: #{@economy.currency_type.titleize}"
    = link_to "Join", @economy.domain, class: 'button radius'    