config/routes.rb
OpenLets::Application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: "omniauth_callbacks", registrations: "registrations" }

  resources :economies

  resources :users do
    member do
      post :direct_transfer
      get  :transfer
    end
    collection do
      get :complete_profile
    end
  end

  resources :members do
    member do
      post :direct_transfer
      get  :transfer
    end
  end
  
  resources :items do
    member do
      get  :purchase_details
      post :time_purchase
      post :purchase
      put  :pause
      put  :activate
    end
    resources :comments, only: [:create]
  end
  
  resources :wishes do
    member do
      put  :pause
      put  :activate
      get  :fulfill
      put  :close
      post :create_wish_offer
    end
  end

  resources :conversations, only: [:index, :show] do
    resources :messages, only: [:create, :index]
    collection do
      get  '/:user_id/new',    to: 'conversations#new',    as: :new
      post '/:user_id/create', to: 'conversations#create', as: :create
    end
  end

  constraints DomainConstraint.new do
    root to: 'pages#economy_home'

    namespace :admin do
      root to: "admin#dashboard", as: :dashboard
      resources :members do
        put :approve
        put :ban
      end
      resources :users do
        member do
          put :approve
          put :ban
        end    
      end
      resources :managers do
        collection do
          put 'add'
          delete 'remove'
        end 
      end
      resources :items do
        member do
          put :activate
          put :pause
          put :ban
        end
      end
      resources :wishes
      resources :comments
      resources :settings do
        collection do
          get :mass_edit
          put :mass_update
        end
      end
      resources :transactions do
        member do
          put :cancel
        end
      end
      resources :categories
      resources :economies, only: :update
    end

  end

  namespace :realm do
    root to: "realm#dashboard", as: :dashboard
    
    resources :admins do
      collection do
        put    :add
        delete :remove
      end      
    end

    resources :users
    resources :economies
  end

  get "pages/terms"
  get "pages/welcome"
  get "pages/faq"

  root to: 'pages#home'
end

app/controllers/admin/transactions_controller.rb
class Admin::TransactionsController < Admin::ResourceController

  def cancel
    resource.cancel!
    flash[:notice] = "Transaction was canceled"
    redirect_to admin_transaction_path(resource)
  end

  private

    def collection
      unless @collection
        result = current_economy ? current_economy.transactions : Transaction
        @collection = result.order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 10)
      end
      @collection
    end

end

app/controllers/realm/transactions_controller.rb
class Realm::TransactionsController < Realm::ResourceController

  def cancel
    resource.cancel!
    flash[:notice] = "Transaction was canceled"
    redirect_to admin_transaction_path(resource)
  end

  private

    def collection
      unless @collection
        result = current_economy ? current_economy.transactions : Transaction
        @collection = result.order(sort_column + ' ' + sort_direction).paginate(page: params[:page], per_page: 10)
      end
      @collection
    end

end

app/views/admin/transactions/_form.slim
= simple_form_for([:admin, resource], wrapper: :foundation_inline) do |f|
  = f.error_notification
  - f.object.errors.full_messages.each do |message|
    p= message
  - resource_class.admin_form_attr_names.each do |attr|
    = form_input(f, attr)
  = f.input :economy_id, as: :hidden, input_html: { value: current_economy.id   }
  .row
    .large-3.columns
    .large-9.columns
      = f.button :submit, t('forms.update')

app/views/admin/transactions/_sidebar.slim
h3.bold= t("filter.filter")
= form_tag filter_path_helper, method: :get do
  = html_select_filter_for(all_transactions, t('filter.id'), :id, :id, :id)
  = html_select_filter_for(all_wallets,      t('filter.sending_wallet_id'), :sending_wallet_id, :id, :user_name)
  = html_select_filter_for(all_wallets,      t('filter.receiving_wallet_id'), :receiving_wallet_id, :id, :user_name)
  = html_select_filter_for(all_items,        t('filter.item_id'), :item_id, :id, :title_with_id)
  = html_select_tag(resource_class.workflow_spec.states.keys.map(&:to_s).map { |state| [state.titleize, state] }, 'workflow_state', t("filter.status"))

app/views/admin/transactions/_table.slim
table.responsive
  thead
    tr
      - attributes.each do |name|
        th= sortable(name, t("tables.#{name.to_s}"))
      th= t('tables.actions')
  tbody
    - filtered_collection.each do |resource|
      tr
        - attributes.each do |name|
          - name = name.to_sym
          td= table_attribute_cell(name, resource)
        - if current_user.has_role?(:admin) && params[:controller] =='admin/users'
          td.roles
            - resource.roles.each do |role|
              span.label.radius
                = role.name


        td.actions
          - if resource.done?
            = link_to cancel_admin_transaction_path(resource), method: :put, class: 'button tiny alert radius', title: t('forms.show')
              i.fa.fa-trash-o
              = t("workflow_state_actions.cancel")

= will_paginate filtered_collection, next_label: '»', previous_label: '«', renderer: FoundationPagination::Rails

app/views/admin/transactions/show.slim
.large-10.columns
  h1.bold
    = t("tables.resource_details", name: t("activerecord.models.#{resource_class.name.downcase}", count: 1 ))
.large-2.columns
  - if resource.done?
    = link_to cancel_admin_transaction_path(resource), method: :put, class: 'button alert radius expand action-button', title: t('forms.show')
      i.fa.fa-trash-o
      = t("workflow_state_actions.cancel")


.large-12.columns
  table.responsive
    tbody
      - (resource_class.attribute_names - ["economy_id"]).each do |attr|
        tr
          th= resource_class.human_attribute_name(attr)
          td= table_attribute_cell(attr.to_sym, resource)